#!/bin/sh
set -eu

: "${MYSTERIUM_SERVICE_BIND_ADDRESS:?runtime did not provide a service bind address}"
: "${MYSTERIUM_SERVICE_PORT:?runtime did not provide a service port}"

while true; do
    {
        printf 'HTTP/1.1 200 OK\r\n'
        printf 'Content-Type: text/plain\r\n'
        printf 'Connection: close\r\n'
        printf '\r\n'
        cat /response.txt
    } | nc -l -s "$MYSTERIUM_SERVICE_BIND_ADDRESS" -p "$MYSTERIUM_SERVICE_PORT"
done
